version: '3.9'
services:
#  caddy
#    name: caddy
#    restart: unless-stopped
#    image: caddy:2.6.4-alpine
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
#      - ./caddy/data:/data
#      - ./caddy/config:/config
#  jupyterhub:
#    name: jupyterhub
#    restart: unless-stopped
#    image: jupyterhub/jupyterhub:4.0
#    ports:
#      - 127.0.0.1:8000:8000
  phg_brapi:
    name: phg_brapi
    image: maizegenetics/phg_brapi
    restart: unless-stopped
    deploy:
        resources:
            limits:
              memory: 175G
            reservations:
              memory: 150G
    volumes:
      - ./brapi:/phg/resources
    environment:
      JAVA_OPTS: "-Xmx170g -Xms170g"
    ports:
       - 8080:8080
  maize_2_1_phg_db:
    name: maize_db
    image: postgres:14
    restart: unless-stopped
    environment:
      - prod.env
    volumes:
      - /mnt/volume_nyc3_01/maize_2_1_phg/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432 # This binds to localhost, not 0.0.0.0