version: '3.9'
services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: caddy:2.6.4-alpine
    networks:
      - hub_net
      - brapi_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/files:/files # To host files we need to be publicly accessible (e.g. Francisco's BrAPI Helper install script)
  jupyterhub:
    container_name: jupyterhub
    restart: unless-stopped
    build:
      context: .
      dockerfile: JupyterHub.dockerfile
    networks:
      - hub_net
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      - "./prod.env:/srv/jupyterhub/prod.env:ro"
      - "/run/user/1001/docker.sock:/var/run/docker.sock" # Access rootless socket associated with user
  phg_brapi:
    container_name: phg_brapi
    image: maizegenetics/phg_brapi:1.4
    restart: unless-stopped
    networks:
      - brapi_net
    deploy:
        resources:
            limits:
              memory: 40G
            reservations:
              memory: 30G
    volumes:
      - ./brapi:/phg/resources
    environment:
      JAVA_OPTS: "-Xmx40g -Xms30g"
    ports:
       - 127.0.0.1:8080:8080
  maize_2_1_phg_db:
    container_name: maize_db
    image: postgres:14
    restart: unless-stopped
    networks:
      - brapi_net
    env_file: prod.env
    volumes:
      - /mnt/volume_nyc3_01/maize_2_1_phg/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

networks:
  hub_net:
    name: hub_net
  brapi_net:
    name: brapi_net