version: '3.9'
services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: caddy:2.6.4-alpine
    networks:
      - hub_net
      - brapi_net
    ports:
      - 80:80
      - 443:443
    env_file: prod.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/files:/files # To host files we need to be publicly accessible (e.g. Francisco's BrAPI Helper install script)
  jupyterhub:
    container_name: jupyterhub
    restart: unless-stopped
    build:
      context: .
      dockerfile: JupyterHub.dockerfile
    networks:
      - hub_net
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      - "./prod.env:/srv/jupyterhub/prod.env:ro"
      - "/run/user/1001/docker.sock:/var/run/docker.sock" # Access rootless socket associated with user

networks:
  hub_net:
    name: hub_net
  brapi_net:
    name: brapi_net
