# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rake"
gem "jekyll", "~> 4.3.2"
gem "jekyll-remote-theme", ">= 0.5.2"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"

# Security updates
gem "concurrent-ruby", ">= 1.3.7"
gem "rubyzip", ">= 3.4.0"
gem "addressable", ">= 2.9.0"
gem "rexml", ">= 3.3.9"
gem "webrick", ">= 1.8.2"
